name: Build Flutter APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17' # تأكد أن هذه النسخة متوافقة مع مشروعك (بعض المشاريع القديمة تحتاج 11)

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # تم التعديل هنا: بناء نسخة Debug لتخطي مشكلة مفاتيح التوقيع الناقصة
      - name: Build APK
        run: flutter build apk --debug

      # تم التعديل هنا: تحديث مسار واسم الملف ليتوافق مع نسخة Debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
